from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI()

# specify the expected structure and data types of the request body. 
# In this case, it expects a JSON object with a single field:
# question: str: A field named question that should be a string. 
class ApiQuestionRequest(BaseModel):
    # This is the only data your endpoint expects in incoming requests.
    question: str = Field(..., 
        example="Hi, how are you?",
        description="In this field, please enter a question in English to be passed to LLM."
    )

class ApiQuestionResponse(BaseModel):
    # This is the only data your endpoint returns in response.
    question: str = Field(..., 
        example="What is the value of a circle's area divided by pi, where the radius of a circle is 2?",
        description="In this field, the content of the oryginal question submitted with the POST /api request will be returned."
    )
    answer: str = Field(..., 
        example="To find the value, you would first calculate the area of the circle , and then divide the result by Pi. The answer is 4.",
        description="In this field, the text generated by the Language Model will be displayed."
    )


# A decorator that creates a route for POST requests to the URL path /question/. 
# function generate_answer defined below is to be called when a POST request to /question/ is received
@app.post("/api/question")
async def apiQuestion(request: ApiQuestionRequest) -> ApiQuestionResponse:
    # Automatically parse the JSON body of incoming requests, validate them against the Question model,
    # and pass a Question instance to the function for access to the request body.

    # TODO: 
    # Begin your code block for LLM interaction.
    original_question = request.question
    my_answer = f'Mock answer to your question: {original_question}'
    # End of your code block

    # Return response
    return ApiQuestionResponse(question=original_question, answer=my_answer)

